Erp::Areas::Country.all.destroy_all
vn = Erp::Areas::Country.create(
  id: 1,
  name: "Việt Nam",
  code: "vn"
)
vn.save

vn.states.destroy_all
vn.states.create(id: 2, name: 'Hà Nội')
vn.states.create(id: 3, name: 'Tp Hồ Chí Minh')
vn.states.create(id: 4, name: 'An Giang')
vn.states.create(id: 5, name: 'Bà Rịa - Vũng Tàu')
vn.states.create(id: 6, name: 'Bình Dương')
vn.states.create(id: 7, name: 'Bình Phước')
vn.states.create(id: 8, name: 'Bình Thuận')
vn.states.create(id: 9, name: 'Bình Định')
vn.states.create(id: 10, name: 'Bạc Liêu')
vn.states.create(id: 11, name: 'Bắc Giang')
vn.states.create(id: 12, name: 'Bắc Kạn')
vn.states.create(id: 13, name: 'Bắc Ninh')
vn.states.create(id: 14, name: 'Bến Tre')
vn.states.create(id: 15, name: 'Cao Bằng')
vn.states.create(id: 16, name: 'Cà Mau')
vn.states.create(id: 17, name: 'Cần Thơ')
vn.states.create(id: 18, name: 'Gia Lai')
vn.states.create(id: 19, name: 'Hà Giang')
vn.states.create(id: 20, name: 'Đồng Tháp')
vn.states.create(id: 21, name: 'Đồng Nai')
vn.states.create(id: 22, name: 'Điện Biên')
vn.states.create(id: 23, name: 'Đắk Nông')
vn.states.create(id: 24, name: 'Đà Nẵng')
vn.states.create(id: 25, name: 'Đaklak')
vn.states.create(id: 26, name: 'Hà Nam')
vn.states.create(id: 27, name: 'Hà Tĩnh')
vn.states.create(id: 28, name: 'Hải Dương')
vn.states.create(id: 29, name: 'Tp.Hải Phòng')
vn.states.create(id: 30, name: 'Hậu Giang')
vn.states.create(id: 31, name: 'Hoà Bình')
vn.states.create(id: 32, name: 'Hưng Yên')
vn.states.create(id: 33, name: 'Khánh Hoà')
vn.states.create(id: 34, name: 'Kiên Giang')
vn.states.create(id: 35, name: 'Kon Tum')
vn.states.create(id: 36, name: 'Lai Châu')
vn.states.create(id: 37, name: 'Lạng Sơn')
vn.states.create(id: 38, name: 'Lào Cai')
vn.states.create(id: 39, name: 'Lâm Đồng')
vn.states.create(id: 40, name: 'Long An')
vn.states.create(id: 41, name: 'Nam Định')
vn.states.create(id: 42, name: 'Nghệ An')
vn.states.create(id: 43, name: 'Ninh Bình')
vn.states.create(id: 44, name: 'Ninh Thuận')
vn.states.create(id: 45, name: 'Phú Thọ')
vn.states.create(id: 46, name: 'Phú Yên')
vn.states.create(id: 47, name: 'Quảng Bình')
vn.states.create(id: 48, name: 'Quảng Nam')
vn.states.create(id: 49, name: 'Quảng Ngãi')
vn.states.create(id: 50, name: 'Quảng Ninh')
vn.states.create(id: 51, name: 'Quảng Trị')
vn.states.create(id: 52, name: 'Sóc Trăng')
vn.states.create(id: 53, name: 'Sơn La')
vn.states.create(id: 54, name: 'Tây Ninh')
vn.states.create(id: 55, name: 'Thanh Hoá')
vn.states.create(id: 56, name: 'Thái Bình')
vn.states.create(id: 57, name: 'Thái Nguyên')
vn.states.create(id: 58, name: 'Thừa Thiên Huế')
vn.states.create(id: 59, name: 'Tiền Giang')
vn.states.create(id: 60, name: 'Trà Vinh')
vn.states.create(id: 61, name: 'Tuyên Quang')
vn.states.create(id: 62, name: 'Vĩnh Long')
vn.states.create(id: 63, name: 'Vĩnh Phúc')
vn.states.create(id: 64, name: 'Yên Bái')

Erp::Areas::District.all.destroy_all
Erp::Areas::District.create(id: 65, name: 'Ba Đình', state_id: 2)
Erp::Areas::District.create(id: 66, name: 'Cầu Giấy', state_id: 2)
Erp::Areas::District.create(id: 67, name: 'Đống Đa', state_id: 2)
Erp::Areas::District.create(id: 68, name: 'Hoàn Kiếm', state_id: 2)
Erp::Areas::District.create(id: 69, name: 'Hai Bà Trưng', state_id: 2)
Erp::Areas::District.create(id: 70, name: 'Hà Đông', state_id: 2)
Erp::Areas::District.create(id: 71, name: 'Hoàng Mai', state_id: 2)
Erp::Areas::District.create(id: 72, name: 'Long Biên', state_id: 2)
Erp::Areas::District.create(id: 73, name: 'Tây Hồ', state_id: 2)
Erp::Areas::District.create(id: 74, name: 'Thanh Xuân', state_id: 2)
Erp::Areas::District.create(id: 75, name: 'Ba Vì', state_id: 2)
Erp::Areas::District.create(id: 76, name: 'Đông Anh', state_id: 2)
Erp::Areas::District.create(id: 77, name: 'Gia Lâm', state_id: 2)
Erp::Areas::District.create(id: 78, name: 'Từ Liêm', state_id: 2)
Erp::Areas::District.create(id: 79, name: 'Thanh Trì', state_id: 2)
Erp::Areas::District.create(id: 80, name: 'Sóc Sơn', state_id: 2)
Erp::Areas::District.create(id: 81, name: 'Phúc Thọ', state_id: 2)
Erp::Areas::District.create(id: 82, name: 'Thạch Thất', state_id: 2)
Erp::Areas::District.create(id: 83, name: 'Đan Phượng', state_id: 2)
Erp::Areas::District.create(id: 84, name: 'Quốc Oai', state_id: 2)
Erp::Areas::District.create(id: 85, name: 'Hoài Đức', state_id: 2)
Erp::Areas::District.create(id: 86, name: 'Thường Tín', state_id: 2)
Erp::Areas::District.create(id: 87, name: 'Phú Xuyên', state_id: 2)
Erp::Areas::District.create(id: 88, name: 'Thanh Oai', state_id: 2)
Erp::Areas::District.create(id: 89, name: 'Chương Mỹ', state_id: 2)
Erp::Areas::District.create(id: 90, name: 'Mỹ Đức', state_id: 2)
Erp::Areas::District.create(id: 91, name: 'Ứng Hòa', state_id: 2)
Erp::Areas::District.create(id: 92, name: 'Tp.Sơn Tây', state_id: 2)
Erp::Areas::District.create(id: 93, name: 'Quận 1', state_id: 3)
Erp::Areas::District.create(id: 94, name: 'Quận 2', state_id: 3)
Erp::Areas::District.create(id: 95, name: 'Quận 3', state_id: 3)
Erp::Areas::District.create(id: 96, name: 'Quận 4', state_id: 3)
Erp::Areas::District.create(id: 97, name: 'Quận 5', state_id: 3)
Erp::Areas::District.create(id: 98, name: 'Quận 6', state_id: 3)
Erp::Areas::District.create(id: 99, name: 'Quận 7', state_id: 3)
Erp::Areas::District.create(id: 100, name: 'Quận 8', state_id: 3)
Erp::Areas::District.create(id: 101, name: 'Quận 9', state_id: 3)
Erp::Areas::District.create(id: 102, name: 'Quận 10', state_id: 3)
Erp::Areas::District.create(id: 103, name: 'Quận 11', state_id: 3)
Erp::Areas::District.create(id: 104, name: 'Quận 12', state_id: 3)
Erp::Areas::District.create(id: 105, name: 'Bình Tân', state_id: 3)
Erp::Areas::District.create(id: 106, name: 'Bình Thạnh', state_id: 3)
Erp::Areas::District.create(id: 107, name: 'Gò Vấp', state_id: 3)
Erp::Areas::District.create(id: 108, name: 'Phú Nhuận', state_id: 3)
Erp::Areas::District.create(id: 109, name: 'Tân Bình', state_id: 3)
Erp::Areas::District.create(id: 110, name: 'Tân Phú', state_id: 3)
Erp::Areas::District.create(id: 111, name: 'Thủ Đức', state_id: 3)
Erp::Areas::District.create(id: 112, name: 'Huyện Nhà Bè', state_id: 3)
Erp::Areas::District.create(id: 113, name: 'Huyện Hóc Môn', state_id: 3)
Erp::Areas::District.create(id: 114, name: 'Huyện Củ Chi', state_id: 3)
Erp::Areas::District.create(id: 115, name: 'Huyện Cần Giờ', state_id: 3)
Erp::Areas::District.create(id: 116, name: 'Huyện Bình Chánh', state_id: 3)
Erp::Areas::District.create(id: 117, name: 'Long Xuyên', state_id: 4)
Erp::Areas::District.create(id: 118, name: 'Châu Đốc', state_id: 4)
Erp::Areas::District.create(id: 119, name: 'Chợ Mới', state_id: 4)
Erp::Areas::District.create(id: 120, name: 'Phú Tân', state_id: 4)
Erp::Areas::District.create(id: 121, name: 'Tân Châu', state_id: 4)
Erp::Areas::District.create(id: 122, name: 'An Phú', state_id: 4)
Erp::Areas::District.create(id: 123, name: 'Tri Tôn', state_id: 4)
Erp::Areas::District.create(id: 124, name: 'Tịnh Biên', state_id: 4)
Erp::Areas::District.create(id: 125, name: 'Châu Thành', state_id: 4)
Erp::Areas::District.create(id: 126, name: 'Châu Phú', state_id: 4)
Erp::Areas::District.create(id: 127, name: 'Thoại Sơn', state_id: 4)
Erp::Areas::District.create(id: 128, name: 'Tp.Vũng Tàu', state_id: 5)
Erp::Areas::District.create(id: 129, name: 'Thị xã Bà Rịa', state_id: 5)
Erp::Areas::District.create(id: 130, name: 'Huyện Châu Đức', state_id: 5)
Erp::Areas::District.create(id: 131, name: 'Huyện Côn Đảo', state_id: 5)
Erp::Areas::District.create(id: 132, name: 'Huyện Long Điền', state_id: 5)
Erp::Areas::District.create(id: 133, name: 'Huyện Đất Đỏ', state_id: 5)
Erp::Areas::District.create(id: 134, name: 'Huyện Tân Thành', state_id: 5)
Erp::Areas::District.create(id: 135, name: 'Huyện Xuyên Mộc', state_id: 5)
Erp::Areas::District.create(id: 136, name: 'Bến Cát', state_id: 6)
Erp::Areas::District.create(id: 137, name: 'Dầu Tiếng', state_id: 6)
Erp::Areas::District.create(id: 138, name: 'Dĩ An', state_id: 6)
Erp::Areas::District.create(id: 139, name: 'Phú Giáo', state_id: 6)
Erp::Areas::District.create(id: 140, name: 'Tân Uyên', state_id: 6)
Erp::Areas::District.create(id: 141, name: 'Thuận An', state_id: 6)
Erp::Areas::District.create(id: 142, name: 'Thủ Dầu Một', state_id: 6)
Erp::Areas::District.create(id: 143, name: 'Đồng Xoài', state_id: 7)
Erp::Areas::District.create(id: 144, name: 'Đồng Phù', state_id: 7)
Erp::Areas::District.create(id: 145, name: 'Phước Long', state_id: 7)
Erp::Areas::District.create(id: 146, name: 'Lộc Ninh', state_id: 7)
Erp::Areas::District.create(id: 147, name: 'Bù Đăng', state_id: 7)
Erp::Areas::District.create(id: 148, name: 'Bình Long', state_id: 7)
Erp::Areas::District.create(id: 149, name: 'Bù Đốp', state_id: 7)
Erp::Areas::District.create(id: 150, name: 'Chơn Thành', state_id: 7)
Erp::Areas::District.create(id: 151, name: 'Hàm Thuận Bắc', state_id: 8)
Erp::Areas::District.create(id: 152, name: 'Tánh Linh', state_id: 8)
Erp::Areas::District.create(id: 153, name: 'Tuy phong', state_id: 8)
Erp::Areas::District.create(id: 154, name: 'Hàm Thuận Nam', state_id: 8)
Erp::Areas::District.create(id: 155, name: 'TP Quy Nhơn', state_id: 9)
Erp::Areas::District.create(id: 156, name: 'An Lão', state_id: 9)
Erp::Areas::District.create(id: 157, name: 'Vĩnh Thạnh', state_id: 9)
Erp::Areas::District.create(id: 158, name: 'Vân Canh', state_id: 9)
Erp::Areas::District.create(id: 159, name: 'Hoài Ân', state_id: 9)
Erp::Areas::District.create(id: 160, name: 'Hoài Nhơn', state_id: 9)
Erp::Areas::District.create(id: 161, name: 'Phù Mỹ', state_id: 9)
Erp::Areas::District.create(id: 162, name: 'Phù Cát', state_id: 9)
Erp::Areas::District.create(id: 163, name: 'Tây Sơn', state_id: 9)
Erp::Areas::District.create(id: 164, name: 'An Nhơn', state_id: 9)
Erp::Areas::District.create(id: 165, name: 'Tuy Phước', state_id: 9)
Erp::Areas::District.create(id: 166, name: 'Bạc Liêu', state_id: 10)
Erp::Areas::District.create(id: 167, name: 'Hoà Bình', state_id: 10)
Erp::Areas::District.create(id: 168, name: 'Đông Hải', state_id: 10)
Erp::Areas::District.create(id: 169, name: 'Giá Rai', state_id: 10)
Erp::Areas::District.create(id: 170, name: 'Hông Dân', state_id: 10)
Erp::Areas::District.create(id: 171, name: 'Phước Long', state_id: 10)
Erp::Areas::District.create(id: 172, name: 'Vĩnh Lợi', state_id: 10)
Erp::Areas::District.create(id: 173, name: 'TP Bắc Giang', state_id: 11)
Erp::Areas::District.create(id: 174, name: 'Lạng Giang', state_id: 11)
Erp::Areas::District.create(id: 175, name: 'Hiệp Hoà', state_id: 11)
Erp::Areas::District.create(id: 176, name: 'Việt Yên', state_id: 11)
Erp::Areas::District.create(id: 177, name: 'Yên Dũng', state_id: 11)
Erp::Areas::District.create(id: 178, name: 'Tân Yên', state_id: 11)
Erp::Areas::District.create(id: 179, name: 'Lục Nam', state_id: 11)
Erp::Areas::District.create(id: 180, name: 'Lục Ngạn', state_id: 11)
Erp::Areas::District.create(id: 181, name: 'Sơn Động', state_id: 11)
Erp::Areas::District.create(id: 182, name: 'Yên Thế', state_id: 11)
Erp::Areas::District.create(id: 183, name: 'Thị xã Bắc Kạn', state_id: 12)
Erp::Areas::District.create(id: 184, name: 'Pác Nặm ', state_id: 12)
Erp::Areas::District.create(id: 185, name: 'Chợ Đồn', state_id: 12)
Erp::Areas::District.create(id: 186, name: 'Chợ Mới', state_id: 12)
Erp::Areas::District.create(id: 187, name: 'Bạch Thông', state_id: 12)
Erp::Areas::District.create(id: 188, name: 'Na Rì', state_id: 12)
Erp::Areas::District.create(id: 189, name: 'Ngân Sơn', state_id: 12)
Erp::Areas::District.create(id: 190, name: 'Ba Bể', state_id: 12)
Erp::Areas::District.create(id: 191, name: 'Thị xã Bắc Ninh', state_id: 13)
Erp::Areas::District.create(id: 192, name: 'Gia Bình', state_id: 13)
Erp::Areas::District.create(id: 193, name: 'Lương Tài', state_id: 13)
Erp::Areas::District.create(id: 194, name: 'Quế Võ', state_id: 13)
Erp::Areas::District.create(id: 195, name: 'Yên Phong', state_id: 13)
Erp::Areas::District.create(id: 196, name: 'Thuận Thành', state_id: 13)
Erp::Areas::District.create(id: 197, name: 'Tiên Du', state_id: 13)
Erp::Areas::District.create(id: 198, name: 'Từ Sơn', state_id: 13)
Erp::Areas::District.create(id: 199, name: 'Thị xã Bến Tre ', state_id: 14)
Erp::Areas::District.create(id: 200, name: 'Châu Thành', state_id: 14)
Erp::Areas::District.create(id: 201, name: 'Chợ Lách', state_id: 14)
Erp::Areas::District.create(id: 202, name: 'Bình Đại', state_id: 14)
Erp::Areas::District.create(id: 203, name: 'Giồng Trôm', state_id: 14)
Erp::Areas::District.create(id: 204, name: 'Mỏ Cày', state_id: 14)
Erp::Areas::District.create(id: 205, name: 'Ba Tri', state_id: 14)
Erp::Areas::District.create(id: 206, name: 'Thạnh Phú', state_id: 14)
Erp::Areas::District.create(id: 207, name: 'Thị Xã Cao Bằng', state_id: 15)
Erp::Areas::District.create(id: 208, name: 'Hoà An ', state_id: 15)
Erp::Areas::District.create(id: 209, name: 'Quảng Uyên', state_id: 15)
Erp::Areas::District.create(id: 210, name: 'Phục Hoà', state_id: 15)
Erp::Areas::District.create(id: 211, name: 'Trà Linh', state_id: 15)
Erp::Areas::District.create(id: 212, name: 'Thạch An', state_id: 15)
Erp::Areas::District.create(id: 213, name: 'Nguyên Bình', state_id: 15)
Erp::Areas::District.create(id: 214, name: 'Bảo Lạc', state_id: 15)
Erp::Areas::District.create(id: 215, name: 'Bảo Lâm', state_id: 15)
Erp::Areas::District.create(id: 216, name: 'Trùng Khánh', state_id: 15)
Erp::Areas::District.create(id: 217, name: 'Tp Cà Mau', state_id: 16)
Erp::Areas::District.create(id: 218, name: 'Đầm Dơi', state_id: 16)
Erp::Areas::District.create(id: 219, name: 'Thới Bình', state_id: 16)
Erp::Areas::District.create(id: 220, name: 'Trần Văn Thời', state_id: 16)
Erp::Areas::District.create(id: 221, name: 'Năm Căn', state_id: 16)
Erp::Areas::District.create(id: 222, name: 'Ngọc Hiến', state_id: 16)
Erp::Areas::District.create(id: 223, name: 'Phú Tân', state_id: 16)
Erp::Areas::District.create(id: 224, name: 'Cái Nước', state_id: 16)
Erp::Areas::District.create(id: 225, name: 'U Minh', state_id: 16)
Erp::Areas::District.create(id: 226, name: 'Ninh Kiều ', state_id: 17)
Erp::Areas::District.create(id: 227, name: 'Bình Thủy', state_id: 17)
Erp::Areas::District.create(id: 228, name: 'Cái Răng', state_id: 17)
Erp::Areas::District.create(id: 229, name: 'Ô Môn', state_id: 17)
Erp::Areas::District.create(id: 230, name: 'Phong Điền', state_id: 17)
Erp::Areas::District.create(id: 231, name: 'Cờ Đỏ', state_id: 17)
Erp::Areas::District.create(id: 232, name: 'Vĩnh Thạnh', state_id: 17)
Erp::Areas::District.create(id: 233, name: 'Thốt Nốt', state_id: 17)
Erp::Areas::District.create(id: 234, name: 'Tp Pleiku', state_id: 18)
Erp::Areas::District.create(id: 235, name: 'An Khê', state_id: 18)
Erp::Areas::District.create(id: 236, name: 'Ayun Pa', state_id: 18)
Erp::Areas::District.create(id: 237, name: 'Đăk Pơ', state_id: 18)
Erp::Areas::District.create(id: 238, name: 'Đăk Đoa', state_id: 18)
Erp::Areas::District.create(id: 239, name: 'A Yun Pa', state_id: 18)
Erp::Areas::District.create(id: 240, name: 'Chư Păh', state_id: 18)
Erp::Areas::District.create(id: 241, name: 'Chư Prông', state_id: 18)
Erp::Areas::District.create(id: 242, name: 'Chư Sê', state_id: 18)
Erp::Areas::District.create(id: 243, name: 'Đức Cơ', state_id: 18)
Erp::Areas::District.create(id: 244, name: 'Ia Grai', state_id: 18)
Erp::Areas::District.create(id: 245, name: 'Kbang', state_id: 18)
Erp::Areas::District.create(id: 246, name: 'Krông Pa', state_id: 18)
Erp::Areas::District.create(id: 247, name: 'Kông Chro', state_id: 18)
Erp::Areas::District.create(id: 248, name: 'Mang Yang', state_id: 18)
Erp::Areas::District.create(id: 249, name: 'Ia Pa', state_id: 18)
Erp::Areas::District.create(id: 250, name: 'Phú Thiện', state_id: 18)
Erp::Areas::District.create(id: 251, name: 'Thị xã Hà Giang', state_id: 19)
Erp::Areas::District.create(id: 252, name: 'Bắc Mê', state_id: 19)
Erp::Areas::District.create(id: 253, name: 'Đồng Văn', state_id: 19)
Erp::Areas::District.create(id: 254, name: 'Hoàng Su Phì', state_id: 19)
Erp::Areas::District.create(id: 255, name: 'Mèo Vạc', state_id: 19)
Erp::Areas::District.create(id: 256, name: 'Quang Bình', state_id: 19)
Erp::Areas::District.create(id: 257, name: 'Quản Bạ', state_id: 19)
Erp::Areas::District.create(id: 258, name: 'Vị Xuyên', state_id: 19)
Erp::Areas::District.create(id: 259, name: 'Xín Mần', state_id: 19)
Erp::Areas::District.create(id: 260, name: 'Yên Minh', state_id: 19)
Erp::Areas::District.create(id: 261, name: 'Bắc Quang', state_id: 19)
Erp::Areas::District.create(id: 262, name: 'Thành phố Cao Lãnh', state_id: 20)
Erp::Areas::District.create(id: 263, name: 'Thị xã Sa Đéc', state_id: 20)
Erp::Areas::District.create(id: 264, name: 'Tháp Mười', state_id: 20)
Erp::Areas::District.create(id: 265, name: 'Thanh Bình', state_id: 20)
Erp::Areas::District.create(id: 266, name: 'Tân Hồng', state_id: 20)
Erp::Areas::District.create(id: 267, name: 'Tam Nông', state_id: 20)
Erp::Areas::District.create(id: 268, name: 'Lấp Vò', state_id: 20)
Erp::Areas::District.create(id: 269, name: 'Lai Vung', state_id: 20)
Erp::Areas::District.create(id: 270, name: 'Hồng Ngự', state_id: 20)
Erp::Areas::District.create(id: 271, name: 'Châu Thành', state_id: 20)
Erp::Areas::District.create(id: 272, name: 'Huyện Cao Lãnh', state_id: 20)
Erp::Areas::District.create(id: 273, name: 'Tp Biên Hòa', state_id: 21)
Erp::Areas::District.create(id: 274, name: 'Long Khánh', state_id: 21)
Erp::Areas::District.create(id: 275, name: 'Long Thành', state_id: 21)
Erp::Areas::District.create(id: 276, name: 'Nhơn Trạch', state_id: 21)
Erp::Areas::District.create(id: 277, name: 'Trảng Bom', state_id: 21)
Erp::Areas::District.create(id: 278, name: 'Thống Nhất', state_id: 21)
Erp::Areas::District.create(id: 279, name: 'Cẩm Mỹ', state_id: 21)
Erp::Areas::District.create(id: 280, name: 'Vĩnh Cửu', state_id: 21)
Erp::Areas::District.create(id: 281, name: 'Xuân Lộc', state_id: 21)
Erp::Areas::District.create(id: 282, name: 'Định Quán', state_id: 21)
Erp::Areas::District.create(id: 283, name: 'Tân Phú', state_id: 21)
Erp::Areas::District.create(id: 284, name: 'Tp Điện Biên Phủ', state_id: 22)
Erp::Areas::District.create(id: 285, name: 'Điện Biên', state_id: 22)
Erp::Areas::District.create(id: 286, name: 'Điện Biên Đông', state_id: 22)
Erp::Areas::District.create(id: 287, name: 'Mường Ảng', state_id: 22)
Erp::Areas::District.create(id: 288, name: 'Mường Chà', state_id: 22)
Erp::Areas::District.create(id: 289, name: 'Mường Nhé', state_id: 22)
Erp::Areas::District.create(id: 290, name: 'Tủa Chùa', state_id: 22)
Erp::Areas::District.create(id: 291, name: 'Tuần Giáo', state_id: 22)
Erp::Areas::District.create(id: 292, name: 'Thị xã Gia Nghĩa', state_id: 23)
Erp::Areas::District.create(id: 293, name: 'Cư Jút', state_id: 23)
Erp::Areas::District.create(id: 294, name: 'Đăk Glong', state_id: 23)
Erp::Areas::District.create(id: 295, name: 'Đăk Mil', state_id: 23)
Erp::Areas::District.create(id: 296, name: 'Đăk Song', state_id: 23)
Erp::Areas::District.create(id: 297, name: 'Krông Nô', state_id: 23)
Erp::Areas::District.create(id: 298, name: 'Tuy Đức', state_id: 23)
Erp::Areas::District.create(id: 299, name: 'Hải Châu', state_id: 24)
Erp::Areas::District.create(id: 300, name: 'hanh Khê', state_id: 24)
Erp::Areas::District.create(id: 301, name: 'Liên Chiểu', state_id: 24)
Erp::Areas::District.create(id: 302, name: 'Sơn Trà', state_id: 24)
Erp::Areas::District.create(id: 303, name: 'Cẩm Lệ', state_id: 24)
Erp::Areas::District.create(id: 304, name: 'Ngũ Hành Sơn', state_id: 24)
Erp::Areas::District.create(id: 305, name: 'Hòa Vang', state_id: 24)
Erp::Areas::District.create(id: 306, name: 'Hoàng Sa', state_id: 24)
Erp::Areas::District.create(id: 307, name: 'Tp Buôn Ma Thuột', state_id: 25)
Erp::Areas::District.create(id: 308, name: 'Krông Buk', state_id: 25)
Erp::Areas::District.create(id: 309, name: 'Krông Pak', state_id: 25)
Erp::Areas::District.create(id: 310, name: 'Lắk', state_id: 25)
Erp::Areas::District.create(id: 311, name: 'Ea Súp', state_id: 25)
Erp::Areas::District.create(id: 312, name: 'Krông Ana', state_id: 25)
Erp::Areas::District.create(id: 313, name: 'Krông Bông', state_id: 25)
Erp::Areas::District.create(id: 314, name: 'Krông Năng', state_id: 25)
Erp::Areas::District.create(id: 315, name: 'Buôn Đôn', state_id: 25)
Erp::Areas::District.create(id: 316, name: 'Ea Kar', state_id: 25)
Erp::Areas::District.create(id: 317, name: 'Cư Kuin', state_id: 25)
Erp::Areas::District.create(id: 318, name: 'Tp Phủ Lý', state_id: 26)
Erp::Areas::District.create(id: 319, name: 'Bình Lục', state_id: 26)
Erp::Areas::District.create(id: 320, name: 'Duy Tiên', state_id: 26)
Erp::Areas::District.create(id: 321, name: 'Kim Bảng', state_id: 26)
Erp::Areas::District.create(id: 322, name: 'ý Nhân', state_id: 26)
Erp::Areas::District.create(id: 323, name: 'Thanh Liêm', state_id: 26)
Erp::Areas::District.create(id: 324, name: 'Tp Hà Tĩnh', state_id: 27)
Erp::Areas::District.create(id: 325, name: 'Thị xã Hồng Lĩnh', state_id: 27)
Erp::Areas::District.create(id: 326, name: 'Kỳ Anh', state_id: 27)
Erp::Areas::District.create(id: 327, name: 'Lộc Hà', state_id: 27)
Erp::Areas::District.create(id: 328, name: 'Thạch Hà', state_id: 27)
Erp::Areas::District.create(id: 329, name: 'Can Lộc', state_id: 27)
Erp::Areas::District.create(id: 330, name: 'Nghi Xuân', state_id: 27)
Erp::Areas::District.create(id: 331, name: 'Đức Thọ', state_id: 27)
Erp::Areas::District.create(id: 332, name: 'Hương Sơn', state_id: 27)
Erp::Areas::District.create(id: 333, name: 'Vũ Quang', state_id: 27)
Erp::Areas::District.create(id: 334, name: 'Cẩm Xuyên', state_id: 27)
Erp::Areas::District.create(id: 335, name: 'Tp Hải Dương', state_id: 28)
Erp::Areas::District.create(id: 336, name: 'Chí Linh', state_id: 28)
Erp::Areas::District.create(id: 337, name: 'Nam Sách', state_id: 28)
Erp::Areas::District.create(id: 338, name: 'Kinh Môn', state_id: 28)
Erp::Areas::District.create(id: 339, name: 'Kim Thành', state_id: 28)
Erp::Areas::District.create(id: 340, name: 'Thanh Hà', state_id: 28)
Erp::Areas::District.create(id: 341, name: 'Ninh Giang', state_id: 28)
Erp::Areas::District.create(id: 342, name: 'Gia Lộc', state_id: 28)
Erp::Areas::District.create(id: 343, name: 'Tứ Kỳ', state_id: 28)
Erp::Areas::District.create(id: 344, name: 'Thanh Miện', state_id: 28)
Erp::Areas::District.create(id: 345, name: 'Cẩm Giàng', state_id: 28)
Erp::Areas::District.create(id: 346, name: 'Bình Giang', state_id: 28)
Erp::Areas::District.create(id: 347, name: 'Dương Kinh', state_id: 29)
Erp::Areas::District.create(id: 348, name: 'Đồ Sơn', state_id: 29)
Erp::Areas::District.create(id: 349, name: 'Hải An', state_id: 29)
Erp::Areas::District.create(id: 350, name: 'Hồng Bàng', state_id: 29)
Erp::Areas::District.create(id: 351, name: 'Kiến An', state_id: 29)
Erp::Areas::District.create(id: 352, name: 'Lê Chân', state_id: 29)
Erp::Areas::District.create(id: 353, name: 'Ngô Quyền', state_id: 29)
Erp::Areas::District.create(id: 354, name: 'An Dương', state_id: 29)
Erp::Areas::District.create(id: 355, name: 'An Lão', state_id: 29)
Erp::Areas::District.create(id: 356, name: 'Bạch Long Vĩ', state_id: 29)
Erp::Areas::District.create(id: 357, name: 'Cát Hải', state_id: 29)
Erp::Areas::District.create(id: 358, name: 'Kiến Thụy', state_id: 29)
Erp::Areas::District.create(id: 359, name: 'Thủy Nguyên', state_id: 29)
Erp::Areas::District.create(id: 360, name: 'Tiên Lãng', state_id: 29)
Erp::Areas::District.create(id: 361, name: 'Vĩnh Bảo', state_id: 29)
Erp::Areas::District.create(id: 362, name: 'Thị xã Vị Thanh', state_id: 30)
Erp::Areas::District.create(id: 363, name: 'Thị xã Ngã Bảy', state_id: 30)
Erp::Areas::District.create(id: 364, name: 'Long Mỹ', state_id: 30)
Erp::Areas::District.create(id: 365, name: 'Phụng Hiệp', state_id: 30)
Erp::Areas::District.create(id: 366, name: 'Châu Thành', state_id: 30)
Erp::Areas::District.create(id: 367, name: 'Châu Thành A', state_id: 30)
Erp::Areas::District.create(id: 368, name: 'Thị xã Hoà Bình', state_id: 31)
Erp::Areas::District.create(id: 369, name: 'Cao Phong', state_id: 31)
Erp::Areas::District.create(id: 370, name: 'Lương Sơn', state_id: 31)
Erp::Areas::District.create(id: 371, name: 'Kỳ Sơn', state_id: 31)
Erp::Areas::District.create(id: 372, name: 'Kim Bôi', state_id: 31)
Erp::Areas::District.create(id: 373, name: 'Lạc Thuỷ', state_id: 31)
Erp::Areas::District.create(id: 374, name: 'Yên Thủy', state_id: 31)
Erp::Areas::District.create(id: 375, name: 'Đà Bắc', state_id: 31)
Erp::Areas::District.create(id: 376, name: 'Mai Châu', state_id: 31)
Erp::Areas::District.create(id: 377, name: 'Thị xã Hưng Yên', state_id: 32)
Erp::Areas::District.create(id: 378, name: 'Ân Thi', state_id: 32)
Erp::Areas::District.create(id: 379, name: 'Khoái Châu', state_id: 32)
Erp::Areas::District.create(id: 380, name: 'Kim Động', state_id: 32)
Erp::Areas::District.create(id: 381, name: 'Mỹ Hào', state_id: 32)
Erp::Areas::District.create(id: 382, name: 'Phù Cừ', state_id: 32)
Erp::Areas::District.create(id: 383, name: 'Tiên Lữ', state_id: 32)
Erp::Areas::District.create(id: 384, name: 'Văn Giang', state_id: 32)
Erp::Areas::District.create(id: 385, name: 'Văn Lâm', state_id: 32)
Erp::Areas::District.create(id: 386, name: 'Yên Mỹ', state_id: 32)
Erp::Areas::District.create(id: 387, name: 'Tp Nha Trang', state_id: 33)
Erp::Areas::District.create(id: 388, name: 'Thị xã Cam Ranh', state_id: 33)
Erp::Areas::District.create(id: 389, name: 'Ninh Hòa', state_id: 33)
Erp::Areas::District.create(id: 390, name: 'Diên Khánh', state_id: 33)
Erp::Areas::District.create(id: 391, name: 'Vạn Ninh', state_id: 33)
Erp::Areas::District.create(id: 392, name: 'Cam Lâm', state_id: 33)
Erp::Areas::District.create(id: 393, name: 'Khánh Sơn', state_id: 33)
Erp::Areas::District.create(id: 394, name: 'Khánh Vĩnh', state_id: 33)
Erp::Areas::District.create(id: 395, name: 'Trường Sa', state_id: 33)
Erp::Areas::District.create(id: 396, name: 'Tp. Rạch Giá ', state_id: 34)
Erp::Areas::District.create(id: 397, name: 'Thị xã Hà Tiên', state_id: 34)
Erp::Areas::District.create(id: 398, name: 'An Biên', state_id: 34)
Erp::Areas::District.create(id: 399, name: 'An Minh', state_id: 34)
Erp::Areas::District.create(id: 400, name: 'Kiên Lương', state_id: 34)
Erp::Areas::District.create(id: 401, name: 'Hòn Đất', state_id: 34)
Erp::Areas::District.create(id: 402, name: 'Tân Hiệp', state_id: 34)
Erp::Areas::District.create(id: 403, name: 'Châu Thành', state_id: 34)
Erp::Areas::District.create(id: 404, name: 'Giồng Riềng', state_id: 34)
Erp::Areas::District.create(id: 405, name: 'Gò Quao', state_id: 34)
Erp::Areas::District.create(id: 406, name: 'Vĩnh Thuận', state_id: 34)
Erp::Areas::District.create(id: 407, name: 'Phú Quốc', state_id: 34)
Erp::Areas::District.create(id: 408, name: 'Kiên Hải', state_id: 34)
Erp::Areas::District.create(id: 409, name: 'U Minh Thượng', state_id: 34)
Erp::Areas::District.create(id: 410, name: 'Thị xã Kontum', state_id: 35)
Erp::Areas::District.create(id: 411, name: 'Đak Hà', state_id: 35)
Erp::Areas::District.create(id: 412, name: 'Đăk Tô', state_id: 35)
Erp::Areas::District.create(id: 413, name: 'Ngọc Hồi', state_id: 35)
Erp::Areas::District.create(id: 414, name: 'Đăk Glei', state_id: 35)
Erp::Areas::District.create(id: 415, name: 'Sa Thầy', state_id: 35)
Erp::Areas::District.create(id: 416, name: 'Kon Rẩy', state_id: 35)
Erp::Areas::District.create(id: 417, name: 'Kon Plong', state_id: 35)
Erp::Areas::District.create(id: 418, name: 'TuMơRông', state_id: 35)
Erp::Areas::District.create(id: 419, name: 'Thị xã Lai Châu', state_id: 36)
Erp::Areas::District.create(id: 420, name: 'Mường Tè', state_id: 36)
Erp::Areas::District.create(id: 421, name: 'Phong Thổ', state_id: 36)
Erp::Areas::District.create(id: 422, name: 'Sìn Hồ', state_id: 36)
Erp::Areas::District.create(id: 423, name: 'Tam Đường', state_id: 36)
Erp::Areas::District.create(id: 424, name: 'Than Uyên', state_id: 36)
Erp::Areas::District.create(id: 425, name: 'Tràng Định', state_id: 37)
Erp::Areas::District.create(id: 426, name: 'Văn Lãng', state_id: 37)
Erp::Areas::District.create(id: 427, name: 'Văn Quan', state_id: 37)
Erp::Areas::District.create(id: 428, name: 'Bình Gia', state_id: 37)
Erp::Areas::District.create(id: 429, name: 'Bắc Sơn', state_id: 37)
Erp::Areas::District.create(id: 430, name: 'Chi Lăng', state_id: 37)
Erp::Areas::District.create(id: 431, name: 'Cao Lộc', state_id: 37)
Erp::Areas::District.create(id: 432, name: 'Lộc Bình', state_id: 37)
Erp::Areas::District.create(id: 433, name: 'Đình Lập', state_id: 37)
Erp::Areas::District.create(id: 434, name: 'Hữu Lũng', state_id: 37)
Erp::Areas::District.create(id: 435, name: 'TP Lào Cai', state_id: 38)
Erp::Areas::District.create(id: 436, name: 'Bát Xát', state_id: 38)
Erp::Areas::District.create(id: 437, name: 'Bắc Hà', state_id: 38)
Erp::Areas::District.create(id: 438, name: 'Bảo Yên', state_id: 38)
Erp::Areas::District.create(id: 439, name: 'Mường Khương', state_id: 38)
Erp::Areas::District.create(id: 440, name: 'Si Ma Cai', state_id: 38)
Erp::Areas::District.create(id: 441, name: 'Sa Pa', state_id: 38)
Erp::Areas::District.create(id: 442, name: 'Văn Bàn', state_id: 38)
Erp::Areas::District.create(id: 443, name: 'Tp Đà Lạt', state_id: 39)
Erp::Areas::District.create(id: 444, name: 'Thị xã Bảo Lộc', state_id: 39)
Erp::Areas::District.create(id: 445, name: 'Lạc Dương', state_id: 39)
Erp::Areas::District.create(id: 446, name: 'Đơn Dương', state_id: 39)
Erp::Areas::District.create(id: 447, name: 'Đức Trọng', state_id: 39)
Erp::Areas::District.create(id: 448, name: 'Lâm Hà', state_id: 39)
Erp::Areas::District.create(id: 449, name: 'Di Linh', state_id: 39)
Erp::Areas::District.create(id: 450, name: 'Bảo Lâm', state_id: 39)
Erp::Areas::District.create(id: 451, name: 'Đạ Huoai', state_id: 39)
Erp::Areas::District.create(id: 452, name: 'Đạ Tẻh', state_id: 39)
Erp::Areas::District.create(id: 453, name: 'Cát Tiên', state_id: 39)
Erp::Areas::District.create(id: 454, name: 'Đam Rôn', state_id: 39)
Erp::Areas::District.create(id: 455, name: 'Thị xã Tân An', state_id: 40)
Erp::Areas::District.create(id: 456, name: 'Bến Lức', state_id: 40)
Erp::Areas::District.create(id: 457, name: 'Cần Đước', state_id: 40)
Erp::Areas::District.create(id: 458, name: 'Cần Giuộc', state_id: 40)
Erp::Areas::District.create(id: 459, name: 'Châu Thành', state_id: 40)
Erp::Areas::District.create(id: 460, name: 'Đức Hòa', state_id: 40)
Erp::Areas::District.create(id: 461, name: 'Đức Huệ', state_id: 40)
Erp::Areas::District.create(id: 462, name: 'Mộc Hóa', state_id: 40)
Erp::Areas::District.create(id: 463, name: 'Tân Hưng', state_id: 40)
Erp::Areas::District.create(id: 464, name: 'Tân Thạnh', state_id: 40)
Erp::Areas::District.create(id: 465, name: 'Tân Trụ', state_id: 40)
Erp::Areas::District.create(id: 466, name: 'Thạnh Hóa', state_id: 40)
Erp::Areas::District.create(id: 467, name: 'Thủ Thừa', state_id: 40)
Erp::Areas::District.create(id: 468, name: 'Vĩnh Hưng', state_id: 40)
Erp::Areas::District.create(id: 469, name: 'Tp. Nam Định', state_id: 41)
Erp::Areas::District.create(id: 470, name: 'Hải Hậu', state_id: 41)
Erp::Areas::District.create(id: 471, name: 'Mỹ Lộc', state_id: 41)
Erp::Areas::District.create(id: 472, name: 'Vụ Bản', state_id: 41)
Erp::Areas::District.create(id: 473, name: 'Giao Thuỷ', state_id: 41)
Erp::Areas::District.create(id: 474, name: 'Ý Yên', state_id: 41)
Erp::Areas::District.create(id: 475, name: 'Nam Trực', state_id: 41)
Erp::Areas::District.create(id: 476, name: 'Trực Ninh', state_id: 41)
Erp::Areas::District.create(id: 477, name: 'Nghĩa Hưng', state_id: 41)
Erp::Areas::District.create(id: 478, name: 'Xuân Trường', state_id: 41)
Erp::Areas::District.create(id: 479, name: 'Thị xã Thái Hòa', state_id: 42)
Erp::Areas::District.create(id: 480, name: 'Tp. Vinh', state_id: 42)
Erp::Areas::District.create(id: 481, name: 'Thị xã Cửa Lò', state_id: 42)
Erp::Areas::District.create(id: 482, name: 'Anh Sơn', state_id: 42)
Erp::Areas::District.create(id: 483, name: 'Diễn Châu', state_id: 42)
Erp::Areas::District.create(id: 484, name: 'Con Cuông', state_id: 42)
Erp::Areas::District.create(id: 485, name: 'Quỳnh Lưu', state_id: 42)
Erp::Areas::District.create(id: 486, name: 'Nam Đàn', state_id: 42)
Erp::Areas::District.create(id: 487, name: 'Đô Lương', state_id: 42)
Erp::Areas::District.create(id: 488, name: 'Hưng Nguyên', state_id: 42)
Erp::Areas::District.create(id: 489, name: 'Nghi Lộc', state_id: 42)
Erp::Areas::District.create(id: 490, name: 'Quế Phong', state_id: 42)
Erp::Areas::District.create(id: 491, name: 'Quỳ Hợp', state_id: 42)
Erp::Areas::District.create(id: 492, name: 'Thanh Chương', state_id: 42)
Erp::Areas::District.create(id: 493, name: 'Tương Dương', state_id: 42)
Erp::Areas::District.create(id: 494, name: 'Kỳ Sơn', state_id: 42)
Erp::Areas::District.create(id: 495, name: 'Nghĩa Đàn', state_id: 42)
Erp::Areas::District.create(id: 496, name: 'Quỳ Châu', state_id: 42)
Erp::Areas::District.create(id: 497, name: 'Tân Kỳ', state_id: 42)
Erp::Areas::District.create(id: 498, name: 'Yên Thành', state_id: 42)
Erp::Areas::District.create(id: 499, name: 'Tp Ninh Bình', state_id: 43)
Erp::Areas::District.create(id: 500, name: 'Thị xã Tam Điệp', state_id: 43)
Erp::Areas::District.create(id: 501, name: 'Gia Viễn', state_id: 43)
Erp::Areas::District.create(id: 502, name: 'Hoa Lư', state_id: 43)
Erp::Areas::District.create(id: 503, name: 'Kim Sơn', state_id: 43)
Erp::Areas::District.create(id: 504, name: 'Nho Quan', state_id: 43)
Erp::Areas::District.create(id: 505, name: 'Yên Khánh', state_id: 43)
Erp::Areas::District.create(id: 506, name: 'Yên Mô', state_id: 43)
Erp::Areas::District.create(id: 507, name: 'Tp Phan Rang-Tháp Chàm', state_id: 44)
Erp::Areas::District.create(id: 508, name: 'Bác Ái', state_id: 44)
Erp::Areas::District.create(id: 509, name: 'Ninh Hải', state_id: 44)
Erp::Areas::District.create(id: 510, name: 'Ninh Phước', state_id: 44)
Erp::Areas::District.create(id: 511, name: 'Ninh Sơn', state_id: 44)
Erp::Areas::District.create(id: 512, name: 'Thuận Bắc', state_id: 44)
Erp::Areas::District.create(id: 513, name: 'Tp Việt Trì', state_id: 45)
Erp::Areas::District.create(id: 514, name: 'Thị xã Phú Thọ', state_id: 45)
Erp::Areas::District.create(id: 515, name: 'Cẩm Khê', state_id: 45)
Erp::Areas::District.create(id: 516, name: 'Đoan Hùng', state_id: 45)
Erp::Areas::District.create(id: 517, name: 'Hạ Hòa', state_id: 45)
Erp::Areas::District.create(id: 518, name: 'Lâm Thao', state_id: 45)
Erp::Areas::District.create(id: 519, name: 'Phù Ninh', state_id: 45)
Erp::Areas::District.create(id: 520, name: 'Tam Nông', state_id: 45)
Erp::Areas::District.create(id: 521, name: 'Tân Sơn', state_id: 45)
Erp::Areas::District.create(id: 522, name: 'Thanh Ba', state_id: 45)
Erp::Areas::District.create(id: 523, name: 'Thanh Sơn', state_id: 45)
Erp::Areas::District.create(id: 524, name: 'Thanh Thủy', state_id: 45)
Erp::Areas::District.create(id: 525, name: 'Yên Lập', state_id: 45)
Erp::Areas::District.create(id: 526, name: 'Tp Tuy Hòa', state_id: 46)
Erp::Areas::District.create(id: 527, name: 'Đông Hòa', state_id: 46)
Erp::Areas::District.create(id: 528, name: 'Đồng Xuân', state_id: 46)
Erp::Areas::District.create(id: 529, name: 'Phú Hòa', state_id: 46)
Erp::Areas::District.create(id: 530, name: 'Sơn Hòa', state_id: 46)
Erp::Areas::District.create(id: 531, name: 'Sông Cầu', state_id: 46)
Erp::Areas::District.create(id: 532, name: 'Sông Hinh', state_id: 46)
Erp::Areas::District.create(id: 533, name: 'Tây Hòa', state_id: 46)
Erp::Areas::District.create(id: 534, name: 'Tuy An', state_id: 46)
Erp::Areas::District.create(id: 535, name: 'Tp Đồng Hới', state_id: 47)
Erp::Areas::District.create(id: 536, name: 'Bố Trạch', state_id: 47)
Erp::Areas::District.create(id: 537, name: 'Lệ Thủy', state_id: 47)
Erp::Areas::District.create(id: 538, name: 'Minh Hóa', state_id: 47)
Erp::Areas::District.create(id: 539, name: 'Quảng Trạch', state_id: 47)
Erp::Areas::District.create(id: 540, name: 'Quảng Ninh', state_id: 47)
Erp::Areas::District.create(id: 541, name: 'Tuyên Hóa', state_id: 47)
Erp::Areas::District.create(id: 542, name: 'Tp Tam Kỳ', state_id: 48)
Erp::Areas::District.create(id: 543, name: 'Tp Hội An', state_id: 48)
Erp::Areas::District.create(id: 544, name: 'Duy Xuyên', state_id: 48)
Erp::Areas::District.create(id: 545, name: 'Đại Lộc', state_id: 48)
Erp::Areas::District.create(id: 546, name: 'Điện Bàn', state_id: 48)
Erp::Areas::District.create(id: 547, name: 'Đông Giang', state_id: 48)
Erp::Areas::District.create(id: 548, name: 'Nam Giang', state_id: 48)
Erp::Areas::District.create(id: 549, name: 'Tây Giang', state_id: 48)
Erp::Areas::District.create(id: 550, name: 'Quế Sơn', state_id: 48)
Erp::Areas::District.create(id: 551, name: 'Hiệp Đức', state_id: 48)
Erp::Areas::District.create(id: 552, name: 'Núi Thành', state_id: 48)
Erp::Areas::District.create(id: 553, name: 'Nam Trà My', state_id: 48)
Erp::Areas::District.create(id: 554, name: 'Bắc Trà My', state_id: 48)
Erp::Areas::District.create(id: 555, name: 'Phú Ninh', state_id: 48)
Erp::Areas::District.create(id: 556, name: 'Phước Sơn', state_id: 48)
Erp::Areas::District.create(id: 557, name: 'Thăng Bình', state_id: 48)
Erp::Areas::District.create(id: 558, name: 'Tiên Phước', state_id: 48)
Erp::Areas::District.create(id: 559, name: 'Nông Sơn', state_id: 48)
Erp::Areas::District.create(id: 560, name: 'Tp Quảng Ngãi', state_id: 49)
Erp::Areas::District.create(id: 561, name: 'Ba Tơ', state_id: 49)
Erp::Areas::District.create(id: 562, name: 'Bình Sơn', state_id: 49)
Erp::Areas::District.create(id: 563, name: 'Đức Phổ', state_id: 49)
Erp::Areas::District.create(id: 564, name: 'Minh Long', state_id: 49)
Erp::Areas::District.create(id: 565, name: 'Mộ Đức', state_id: 49)
Erp::Areas::District.create(id: 566, name: 'Sơn Hà', state_id: 49)
Erp::Areas::District.create(id: 567, name: 'Sơn Tây', state_id: 49)
Erp::Areas::District.create(id: 568, name: 'Sơn Tịnh', state_id: 49)
Erp::Areas::District.create(id: 569, name: 'Tây Trà', state_id: 49)
Erp::Areas::District.create(id: 570, name: 'Trà Bồng', state_id: 49)
Erp::Areas::District.create(id: 571, name: 'Tư Nghĩa', state_id: 49)
Erp::Areas::District.create(id: 572, name: 'Lý Sơn', state_id: 49)
Erp::Areas::District.create(id: 573, name: 'Tp Hạ Long', state_id: 50)
Erp::Areas::District.create(id: 574, name: 'Thị xã Cẩm Phả', state_id: 50)
Erp::Areas::District.create(id: 575, name: 'Thị xã Móng Cái', state_id: 50)
Erp::Areas::District.create(id: 576, name: 'Thị xã Uông Bí', state_id: 50)
Erp::Areas::District.create(id: 577, name: 'Ba Chẽ', state_id: 50)
Erp::Areas::District.create(id: 578, name: 'Bình Liêu', state_id: 50)
Erp::Areas::District.create(id: 579, name: 'Đầm Hà', state_id: 50)
Erp::Areas::District.create(id: 580, name: 'Đông Triều', state_id: 50)
Erp::Areas::District.create(id: 581, name: 'Hải Hà', state_id: 50)
Erp::Areas::District.create(id: 582, name: 'Hoành Bồ', state_id: 50)
Erp::Areas::District.create(id: 583, name: 'Tiên Yên', state_id: 50)
Erp::Areas::District.create(id: 584, name: 'Vân Đồn', state_id: 50)
Erp::Areas::District.create(id: 585, name: 'Yên Hưng', state_id: 50)
Erp::Areas::District.create(id: 586, name: 'Thị xã Đông Hà', state_id: 51)
Erp::Areas::District.create(id: 587, name: 'Thị xã Quảng Trị', state_id: 51)
Erp::Areas::District.create(id: 588, name: 'Cam Lộ', state_id: 51)
Erp::Areas::District.create(id: 589, name: 'Cồn Cỏ', state_id: 51)
Erp::Areas::District.create(id: 590, name: 'Đa Krông', state_id: 51)
Erp::Areas::District.create(id: 591, name: 'Gio Linh', state_id: 51)
Erp::Areas::District.create(id: 592, name: 'Hải Lăng', state_id: 51)
Erp::Areas::District.create(id: 593, name: 'Hướng Hóa', state_id: 51)
Erp::Areas::District.create(id: 594, name: 'Triệu Phong', state_id: 51)
Erp::Areas::District.create(id: 595, name: 'Vĩnh Linh', state_id: 51)
Erp::Areas::District.create(id: 596, name: 'Tp Sóc Trăng', state_id: 52)
Erp::Areas::District.create(id: 597, name: 'Long Phú', state_id: 52)
Erp::Areas::District.create(id: 598, name: 'Cù Lao Dung', state_id: 52)
Erp::Areas::District.create(id: 599, name: ' Mỹ Tú', state_id: 52)
Erp::Areas::District.create(id: 600, name: 'Thạnh Trị', state_id: 52)
Erp::Areas::District.create(id: 601, name: 'Vĩnh Châu', state_id: 52)
Erp::Areas::District.create(id: 602, name: 'Ngã Năm', state_id: 52)
Erp::Areas::District.create(id: 603, name: 'Kế Sách', state_id: 52)
Erp::Areas::District.create(id: 604, name: 'Mỹ Xuyên', state_id: 52)
Erp::Areas::District.create(id: 605, name: 'Tp Sơn La', state_id: 53)
Erp::Areas::District.create(id: 606, name: 'Quỳnh Nhai', state_id: 53)
Erp::Areas::District.create(id: 607, name: 'Mường La', state_id: 53)
Erp::Areas::District.create(id: 608, name: 'Thuận Châu', state_id: 53)
Erp::Areas::District.create(id: 609, name: 'Phù Yên', state_id: 53)
Erp::Areas::District.create(id: 610, name: 'Bắc Yên', state_id: 53)
Erp::Areas::District.create(id: 611, name: 'Mai Sơn', state_id: 53)
Erp::Areas::District.create(id: 612, name: 'Sông Mã', state_id: 53)
Erp::Areas::District.create(id: 613, name: 'Yên Châu', state_id: 53)
Erp::Areas::District.create(id: 614, name: 'Mộc Châu', state_id: 53)
Erp::Areas::District.create(id: 615, name: 'Sốp Cộp', state_id: 53)
Erp::Areas::District.create(id: 616, name: 'Thị xã Tây Ninh', state_id: 54)
Erp::Areas::District.create(id: 617, name: 'Tân Biên', state_id: 54)
Erp::Areas::District.create(id: 618, name: 'Tân Châu', state_id: 54)
Erp::Areas::District.create(id: 619, name: 'Dương Minh Châu', state_id: 54)
Erp::Areas::District.create(id: 620, name: 'Châu Thành', state_id: 54)
Erp::Areas::District.create(id: 621, name: 'Hòa Thành', state_id: 54)
Erp::Areas::District.create(id: 622, name: 'Bến Cầu', state_id: 54)
Erp::Areas::District.create(id: 623, name: 'Gò Dầu', state_id: 54)
Erp::Areas::District.create(id: 624, name: 'Trảng Bàng', state_id: 54)
Erp::Areas::District.create(id: 625, name: 'Tp Thanh Hóa', state_id: 55)
Erp::Areas::District.create(id: 626, name: 'Thị xã Bỉm Sơn', state_id: 55)
Erp::Areas::District.create(id: 627, name: 'Thị xã Sầm Sơn', state_id: 55)
Erp::Areas::District.create(id: 628, name: 'Bá Thước', state_id: 55)
Erp::Areas::District.create(id: 629, name: 'Cẩm Thủy', state_id: 55)
Erp::Areas::District.create(id: 630, name: 'Đông Sơn', state_id: 55)
Erp::Areas::District.create(id: 631, name: 'Hà Trung', state_id: 55)
Erp::Areas::District.create(id: 632, name: 'Hậu Lộc', state_id: 55)
Erp::Areas::District.create(id: 633, name: 'Hoằng Hóa', state_id: 55)
Erp::Areas::District.create(id: 634, name: 'Lang Chánh', state_id: 55)
Erp::Areas::District.create(id: 635, name: 'Mường Lát', state_id: 55)
Erp::Areas::District.create(id: 636, name: 'Nga Sơn', state_id: 55)
Erp::Areas::District.create(id: 637, name: 'Ngọc Lặc', state_id: 55)
Erp::Areas::District.create(id: 638, name: 'Như Thanh', state_id: 55)
Erp::Areas::District.create(id: 639, name: 'Như Xuân', state_id: 55)
Erp::Areas::District.create(id: 640, name: 'Nông Cống', state_id: 55)
Erp::Areas::District.create(id: 641, name: 'Quan Hóa', state_id: 55)
Erp::Areas::District.create(id: 642, name: 'Quan Sơn', state_id: 55)
Erp::Areas::District.create(id: 643, name: 'Quảng Xương', state_id: 55)
Erp::Areas::District.create(id: 644, name: 'Thạch Thành', state_id: 55)
Erp::Areas::District.create(id: 645, name: 'Thiệu Hóa', state_id: 55)
Erp::Areas::District.create(id: 646, name: 'Thọ Xuân', state_id: 55)
Erp::Areas::District.create(id: 647, name: 'Thường Xuân', state_id: 55)
Erp::Areas::District.create(id: 648, name: 'Tĩnh Gia', state_id: 55)
Erp::Areas::District.create(id: 649, name: 'Triệu Sơn', state_id: 55)
Erp::Areas::District.create(id: 650, name: 'Vĩnh Lộc', state_id: 55)
Erp::Areas::District.create(id: 651, name: 'Yên Định', state_id: 55)
Erp::Areas::District.create(id: 652, name: 'Tp Thái Bình', state_id: 56)
Erp::Areas::District.create(id: 653, name: 'Thái Thuỵ', state_id: 56)
Erp::Areas::District.create(id: 654, name: 'Tiền Hải', state_id: 56)
Erp::Areas::District.create(id: 655, name: 'Đông Hưng', state_id: 56)
Erp::Areas::District.create(id: 656, name: 'Vũ Thư', state_id: 56)
Erp::Areas::District.create(id: 657, name: 'Kiến Xương', state_id: 56)
Erp::Areas::District.create(id: 658, name: 'Quỳnh Phụ', state_id: 56)
Erp::Areas::District.create(id: 659, name: 'Hưng Hà', state_id: 56)
Erp::Areas::District.create(id: 660, name: 'Tp Thái Nguyên', state_id: 57)
Erp::Areas::District.create(id: 661, name: 'Thị xã Sông Công', state_id: 57)
Erp::Areas::District.create(id: 662, name: 'Phổ Yên', state_id: 57)
Erp::Areas::District.create(id: 663, name: 'Phú Bình', state_id: 57)
Erp::Areas::District.create(id: 664, name: ' Đồng Hỷ', state_id: 57)
Erp::Areas::District.create(id: 665, name: 'Võ Nhai', state_id: 57)
Erp::Areas::District.create(id: 666, name: 'Định Hóa', state_id: 57)
Erp::Areas::District.create(id: 667, name: 'Đại Từ', state_id: 57)
Erp::Areas::District.create(id: 668, name: 'Phú Lương', state_id: 57)
Erp::Areas::District.create(id: 669, name: 'Thành phố Huế', state_id: 58)
Erp::Areas::District.create(id: 670, name: 'A Lưới', state_id: 58)
Erp::Areas::District.create(id: 671, name: 'Phú Lộc', state_id: 58)
Erp::Areas::District.create(id: 672, name: 'Hương Thủy', state_id: 58)
Erp::Areas::District.create(id: 673, name: 'Phú Vang', state_id: 58)
Erp::Areas::District.create(id: 674, name: 'Hương Trà', state_id: 58)
Erp::Areas::District.create(id: 675, name: 'Quảng Điền', state_id: 58)
Erp::Areas::District.create(id: 676, name: 'Nam Đông', state_id: 58)
Erp::Areas::District.create(id: 677, name: 'Tp Mỹ Tho', state_id: 59)
Erp::Areas::District.create(id: 678, name: 'Thị xã Gò Công', state_id: 59)
Erp::Areas::District.create(id: 679, name: 'Cái Bè', state_id: 59)
Erp::Areas::District.create(id: 680, name: 'Cai Lậy', state_id: 59)
Erp::Areas::District.create(id: 681, name: 'Châu Thành', state_id: 59)
Erp::Areas::District.create(id: 682, name: 'Tân Phước', state_id: 59)
Erp::Areas::District.create(id: 683, name: 'Chợ Gạo', state_id: 59)
Erp::Areas::District.create(id: 684, name: 'Gò Công Tây', state_id: 59)
Erp::Areas::District.create(id: 685, name: 'Gò Công Đông', state_id: 59)
Erp::Areas::District.create(id: 686, name: 'Tân Phú Đông', state_id: 59)
Erp::Areas::District.create(id: 687, name: 'Thị xã Trà Vinh', state_id: 60)
Erp::Areas::District.create(id: 688, name: 'Trà Cú', state_id: 60)
Erp::Areas::District.create(id: 689, name: 'Duyên Hải', state_id: 60)
Erp::Areas::District.create(id: 690, name: 'Cầu Ngang', state_id: 60)
Erp::Areas::District.create(id: 691, name: 'Châu Thành', state_id: 60)
Erp::Areas::District.create(id: 692, name: 'Cầu Kè', state_id: 60)
Erp::Areas::District.create(id: 693, name: 'Tiểu Cần', state_id: 60)
Erp::Areas::District.create(id: 694, name: 'Càng Long ', state_id: 60)
Erp::Areas::District.create(id: 695, name: 'Thị xã Tuyên Quang ', state_id: 61)
Erp::Areas::District.create(id: 696, name: 'Na Hang ', state_id: 61)
Erp::Areas::District.create(id: 697, name: 'Chiêm Hoá', state_id: 61)
Erp::Areas::District.create(id: 698, name: 'Hàm Yên ', state_id: 61)
Erp::Areas::District.create(id: 699, name: 'Yên Sơn ', state_id: 61)
Erp::Areas::District.create(id: 700, name: 'Sơn Dương ', state_id: 61)
Erp::Areas::District.create(id: 701, name: 'Thị xã Vĩnh Long', state_id: 62)
Erp::Areas::District.create(id: 702, name: 'Long Hồ', state_id: 62)
Erp::Areas::District.create(id: 703, name: 'Mang Thít', state_id: 62)
Erp::Areas::District.create(id: 704, name: 'Tam Bình', state_id: 62)
Erp::Areas::District.create(id: 705, name: 'Bình Minh', state_id: 62)
Erp::Areas::District.create(id: 706, name: 'Vũng Liêm', state_id: 62)
Erp::Areas::District.create(id: 707, name: 'Trà Ôn', state_id: 62)
Erp::Areas::District.create(id: 708, name: 'Tp Vĩnh Yên', state_id: 63)
Erp::Areas::District.create(id: 709, name: 'Thị xã Phúc Yên', state_id: 63)
Erp::Areas::District.create(id: 710, name: 'Vĩnh Tường', state_id: 63)
Erp::Areas::District.create(id: 711, name: 'Bình Xuyên', state_id: 63)
Erp::Areas::District.create(id: 712, name: 'Yên Lạc', state_id: 63)
Erp::Areas::District.create(id: 713, name: 'Tam Dương', state_id: 63)
Erp::Areas::District.create(id: 714, name: 'Tam Đảo ', state_id: 63)
Erp::Areas::District.create(id: 715, name: 'Lập Thạch', state_id: 63)
Erp::Areas::District.create(id: 716, name: 'Tp Yên Bái', state_id: 64)
Erp::Areas::District.create(id: 717, name: 'Thị xã Nghĩa Lộ', state_id: 64)
Erp::Areas::District.create(id: 718, name: 'Lục Yên', state_id: 64)
Erp::Areas::District.create(id: 719, name: 'Mù Cang Chải', state_id: 64)
Erp::Areas::District.create(id: 720, name: 'Trấn Yên', state_id: 64)
Erp::Areas::District.create(id: 721, name: 'Trạm Tấu', state_id: 64)
Erp::Areas::District.create(id: 722, name: 'Văn Chấn', state_id: 64)
Erp::Areas::District.create(id: 723, name: 'Văn Yên', state_id: 64)
Erp::Areas::District.create(id: 724, name: 'Yên Bình', state_id: 64)
